export const BATCH_ACTIONS = 'BATCH_ACTIONS';

export const ADD_DELIVERY = 'ADD_DELIVERY';
export const ADD_DRIVER = 'ADD_DRIVER';

export const CREATE_ROUTE = 'CREATE_ROUTE';
export const CLEAR_ROUTES = 'CLEAR_ROUTES';

export const ADD_DELIVERY_TOUR = 'ADD_DELIVERY_TOUR';
export const ADD_ROUTE_TOUR = 'ADD_ROUTE_TOUR';

export const ENABLE_ROUTING_BUTTON = 'ENABLE_ROUTING_BUTTON';
export const DISABLE_ROUTING_BUTTON = 'DISABLE_ROUTING_BUTTON';

export const SELECT_NAVIGATION_TAB = 'SELECT_NAVIGATION_TAB';

export const SELECT_DRIVER = 'SELECT_DRIVER';
export const DESELECT_DRIVER = 'DESELECT_DRIVER';

export const SELECT_DELIVERY = 'SELECT_DELIVERY';
export const DESELECT_DELIVERY = 'DESELECT_DELIVERY';

export const SELECT_ROUTE = 'SELECT_ROUTE';
export const DESELECT_ROUTE = 'DESELECT_ROUTE';

export const START_CREATE_ROUTE_REQUEST = 'START_CREATE_ROUTE_REQUEST';
export const END_CREATE_ROUTE_REQUEST = 'END_CREATE_ROUTE_REQUEST';
